[options]
work_mode = "sys"
library = "Soup"
version = "2.4"
external_libraries = [
   "GLib",
   "GObject",
   "Gio",
]

ignore = [
  "Soup.MICRO_VERSION",
  "Soup.MINOR_VERSION",
  "Soup.VERSION_MIN_REQUIRED",
]
