// Feel free to edit this file, it won't be regenerated by gir generator unless removed.

#define LIBSOUP_USE_UNSTABLE_REQUEST_API
#include <libsoup/soup.h>
#include <libsoup/soup-password-manager.h>
#include <libsoup/soup-requester.h>
